      <footer>
      	<div class="container">
      		<div class="row">
                        <div class="col-sm-8 hidden-xs">
                              <div class="row">
                  			<div class="col-sm-3 hidden-xs">
                  			
                  				<span class="foot_title">Waarom</span>

                  				<ul>
                  					<li>
                  						<a href="waarom-act" title="Act! De nummer 1 CRM voor klant- en contactbeheer">Waarom Act!</a>
                  					</li>
                  					<li>
                  						<a href="waarom-act/installatiemogelijkheden" title="Act! in de Cloud of op kantoor: kies hoe u Act! installeert">Installatiemogelijkheden
            </a>
                  					</li>
                  					<li>
                  						<a href="testimonials-alle" title="Act! Testimonials over CRM voor klant- en contactbeheer">Wat onze klanten zeggen</a>
                  					</li>

                  				</ul>

                  			</div>

                  			<div class="col-sm-3 hidden-xs">

                  				<span class="foot_title">Producten</span>

                  				<ul>
                  					<li>
                  						<a href="producten/act-premium" title="Act! Premium: mobiel klant- en contactbeheer (CRM)">Act! Premium</a>
                  					</li>
                  				</ul>

                  			</div>

                  			

                                    <div class="col-sm-3 hidden-xs">
                                          <span class="foot_title"><a class="footwhite" href="http://www.swiftpage.com/" target="_blank">Over ons
            </a></span>
                                          <ul>
                                                
                                                      <li>  <a href="http://www.swiftpage.com/en-us/about/legal.shtml" target="_blank">Juridische informatie</a></li>
                                          </ul>

                                    </div>

                                    <div class="col-sm-3 hidden-xs">
                                          <span class="foot_title">Partners</span>
                                          <ul>
                                                <li>
                                                      <a href="partners-kaart" title="Find a local partner to help get you up and running effectively and keep you running smoothly">Zoek een partner</a>
                                                </li>
                                          </ul>

                                    </div>
                              </div>
                              <div class="row">
                                    <div class="col-sm-10 footer-note">
                                          <br />
                                          Swiftpage biedt lokalisering en ondersteuning voor Act! in het Engels, Frans en Duits. Ons wereldwijde netwerk van Act! Certified Consultants levert oplossingen voor een naadloze integratie van automatische vertalingen in klantapplicaties, workflows en diensten en biedt ondersteuning in uw taal.
                                    </div>
                              </div>
                        </div>

      			<div class=" col-sm-2 social col-sm-offset-2">
				
      				<a href="https://www.youtube.com/user/ActStory" target="_blank" class="social-roll yt">Youtube</a>
      				<a href="https://www.linkedin.com/groups/?gid=1914089" class="social-roll linkd" target="_blank">LinkedIn</a>
      				<a href="https://twitter.com/actstory" class="social-roll twit" target="_blank">Twitter</a>
      				<a href="https://www.facebook.com/actcrm" class="social-roll fb" target="_blank">Facebook</a>

                              <br><br><br>

                            

                              <img src="/nl-nl/img/cards.jpg" style="max-width:100%;height:auto" class="hidden-xs"/>  

                              <br><br>   

                               <span class="copyright"> Copyright <strong>Swiftpage ltd 2015 </strong> </span>

                             

      			</div>
      		</div>
      	</div>
      </footer>
      <!-- ELOQUA -->
<script type="text/javascript">
var _elqQ = _elqQ || [];
_elqQ.push(['elqSetSiteId', '1966950654']);
_elqQ.push(['elqTrackPageViewDisplayOptInBannerForAll']);
(function () {
function async_load() {
var s = document.createElement('script');
s.type = 'text/javascript';
s.async = true; s.src = '//img03.en25.com/i/elqCfg.min.js';
var x = document.getElementsByTagName('script')[0];
x.parentNode.insertBefore(s, x);
}
if (window.addEventListener) window.addEventListener('DOMContentLoaded', async_load, false);
else if (window.attachEvent) window.attachEvent('onload', async_load);
})();
function elqVisitorTrackingOptIn() {
_elqQ.push(['elqOptIn']);
}
function elqVisitorTrackingOptOut() {
_elqQ.push(['elqOptOut']);
}
</script>
<!-- .end ELOQUA -->
      <script type="text/javascript">
      function elqCreateOptInBanner() {
      if (navigator.appVersion.indexOf('MSIE') != -1) {
      var css = '.cookieBanner {z-index:30; position: absolute; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
      }
      else {
      var css = '.cookieBanner {z-index:30; position: fixed; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
      }
      var style = document.createElement('STYLE');
      style.type = 'text/css';
      if (style.styleSheet) {
      style.styleSheet.cssText = css;
      } else {
      style.appendChild(document.createTextNode(css));
      }
      var head = document.getElementsByTagName('head')[0];
      head.appendChild(style);
      var div = document.createElement('div');
      div.setAttribute('id', 'cookieBannerDiv');
      div.className = 'cookieBanner';
      div.innerHTML = '<div class="cookieBannerText">Onze website gebruikt cookies om de functionaliteit voor u aan te passen en de website gebruiksvriendelijk te maken. Lees voor meer informatie ons  <a href="cookiebeleid/" style="text-decoration:underline;">cookiebeleid</a>. Door deze website te gebruiken geeft u aan dat u akkoord gaat met ons gebruik van cookies.</div><div class="cookieClose" onclick="document.getElementById(\'cookieBannerDiv\').style.display = \'none\';">x</div>';
      document.body.appendChild(div);

            // Hide alert after 20 seconds
            /*setTimeout(function(){
                  $('.cookieClose').click();
            }, 20000);*/
      }
      </script>