
<!--START FIXED NAV WRAPPER-->        
<div class="fixed-wrapper">
  	<div class="container mobile-menu">

		  		<div class="col-md-2 col-lg-1 col-xs-12 col-sm-2 ">
			  		<div class="row">
            		<div class="col-xs-10 col-md-12">
							<a href="/nl-nl/"><img src="/nl-nl/img/act-klant-en-contactbeheer-logonew.gif" alt="Logo Act! klant- en contactbeheer" class="actlogo"></a>
					</div>
					<div class="trigger-overlay visible-xs col-xs-2" id="mobile_btn">
		        	    <div class="menu_icon"></div>
		        	    <div class="menu_icon_close"></div>
		        	</div>
			  		</div>
				</div>

				<nav class="col-md-4 col-sm-10 col-lg-6 nav-collapse">
					<ul>
						<li><a href="waarom-act" title="Act! De nummer 1 CRM voor klant- en contactbeheer">Waarom&nbsp;&nbsp;<span class="down_arrow"></span></a>
							   <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="waarom-act" title="Act! De nummer 1 CRM voor klant- en contactbeheer">Waarom Act!</a></li>
					  		 	<li><a href="waarom-act/installatiemogelijkheden" title="Act! in de Cloud of op kantoor: kies hoe u Act! installeert">Installatiemogelijkheden</a></li>
								<li><a href="testimonials-alle" title="Act! Testimonials over CRM voor klant- en contactbeheer">Wat onze klanten zeggen</a></li>
								
								
								 
					  		</ul>
						</li>
						<li><a title="Compare features and benefits between Act! versions">Producten&nbsp;&nbsp;<span class="down_arrow"></span></a>
                            <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<!--<li><a href="products" title="Compare features and benefits between Act! versions">Compare products</a></li>-->
					  		 	<!--<li><a href="products/act-pro" title="Find out more about Act! Pro. Designed for individuals and teams of up to 10 users.">Act! Pro</a></li>-->
					  		 	<li><a href="producten/act-premium" title="Act! Premium: mobiel klant- en contactbeheer (CRM)">Act! Premium</a></li>
								<!--<li><a href="products/act-essentials" title="Find out more about Act! Cloud Essentials. Designed for individuals and startups">Act! Cloud Essentials</a></li>-->
					  		 	<!--<li><a href="products/upgrade" title="What's new in the latest release of Act!">What's new in Act! v17</a></li>-->
					  		</ul>
					  	</li>
					  	<!--<li><a href="support" title="Software support options">Support</a>
						
								<ul>
									<li><a href="support" title="Software support options">Business Care</a></li>
									<li><a href="support/training-opportunities" title="Online or onsite training">Training opportunities</a></li>
									<li><a href="support/obsolescence-policies" title="Supported and unsupported versions">Obsolescence Policy</a></li>
									<li><a href="support/downloads/emea" title="Download software hotfixes, updates and feature packs" >Download Centre</a></li>
									<li><a target="_blank" href="http://www.act.com/support/getting-started/">Resource Centre</a></li>
									<li><a href="http://kb.act.com" target="_blank">Knowledgebase</a></li>

								</ul>
						</li>-->
					  	<li><a href="partners-kaart" title="Zoek een Act! Certified Consultant (ACC)">Partners</a></li>
                		<li><a href="http://community.act.com/" target="_blank">Forum</a></li>
                		<!--<li><a href="contact-us" title="Get in touch by telephone, email or send us a message">Contact</a></li>-->
					</ul>
					</ul>
					<br style="clear:both">
				</nav>

				
				<div class="col-md-4 col-sm-8 tl_links hidden-xs">
                  	<a href="demo" title="Laat u adviseren door een Act! productexpert" class="btn btn-second">demo aanvragen</a> 
				  	<a href="partners-kaart" title="Zoek een Act! Certified Consultant (ACC)" class="btn btn-second">partner zoeken</a>
				</div>
				<div class="col-sm-1 col-md-1">
					<nav class="langmenu">
						<ul>
			   			 	<li >Taal: <strong class="lang_menu">Nederlands <span class="down_arrow hidden-sm"></span></strong>
			   			 		<ul>
			   			 			<li><a href="http://www.act.com/en-uk/" lang="en" hreflang="en" title="Act! CRM Software">English</a></li>
			   			 			<li><a href="http://www.act.com/de-de/" lang="de" hreflang="de" title="Act! CRM Software">Deutsch</a></li>
			   			 			<li><a href="http://www.act.com/fr-fr/" lang="fr" hreflang="fr" title="Act! Logiciel CRM">Fran&#231;ais</a></li>
			   			 			<li><a href="http://www.act.com/?regLang=en-US" lang="en-us" hreflang="en-us" title="Act! CRM Software">U.S. English</a></li>
			   			 			
			   			 		</ul>
			   			 	</li>
						</ul>
					</nav>
				</div>

    </div>
</div>
<div class="spacer"></div>
<!--END FIXED WRAPPER-->