        <div class="slider-container">
          	<div class="slider ">
            		<ul>
					<li class="cta">
						<div class="slider-bg">
							<img src="/nl-nl/img/tevreden-zakelijke-gebruikers-act.jpg" alt="Tevreden gebruikers van Act! contactbeheer" />
						</div>

						<div class="slider-overlay">
							<div class="container ">
								<div class="row section">
								  	<div class="col-sm-8 col-left bottom mb-center ">
								    		<h1 class="large_strapline_home semibold"><strong>Act! is de nummer 1 </strong>oplossing voor klant - <br />en contactbeheer</h1>
										 <div class="btn-bottom">
								      		
								      		<a href="demo" title="Laat u adviseren door een Act! productexpert" class="btn-primary btn">demo aanvragen</a>
								      		<a href="partners-kaart" title="Zoek een Act! Certified Consultant (ACC)" class="btn-second btn">partner zoeken</a>
									  	</div>
									 </div>
									 <div class="col-sm-4 imagefix hidden-xs">

                      				 </div>
								</div>
							</div>
						</div>
					</li>



					<li class="cta">
						<div class="slider-bg">
							<img src="/nl-nl/img/act-voor-reebok-fitnesscentrum.jpg" alt="Testimonial Act! contactbeheer van Reebok fitnesscentrum" />
						</div>
					<div class="slider-overlay">
						<div class="container ">
							<div class="row section">
							  	<div class="col-sm-10  white bottom col-left mb-center col-xs-12">
							    		<span class="large_strapline_home semibold"> Act! De ultieme salestool</span>
							   <img src="/nl-nl/img/reebok.png" alt="" width="160" class="hidden-xs">
							   <br> <br>
									 <div class="btn-bottom white">
							      		<a href="testimonials/reebok" title="Act! CRM geeft Reebok Sports Club een voorsprong" class="btn-primary btn">lees verder</a>
							      		<a href="testimonials-alle" title="Act! Testimonials over CRM voor klant- en contactbeheer" class="btn-second btn">bekijk alle testimonials</a>
								  	</div>
								 </div>
								  <div class="col-sm-4 imagefix hidden-xs"></div>
							</div>
						</div>
						</div>
					</li>


					<li class="cta">
						<div class="slider-bg">
							<img src="/nl-nl/img/sales-onderweg-gebruikt-act.jpg" alt="Lid van salesteam gebruikt Act!" />
						</div>

						<div class="slider-overlay">
							<div class="container ">
								<div class="row">
								  	<div class="col-sm-8 bottom col-left mb-center col-xs-12">
									    <span class="large_strapline_home semibold"><strong>Op kantoor of in <br>de Cloud:</strong><br>de keuze is aan u</span>
										<div class="btn-bottom">
										    <a a href="waarom-act/installatiemogelijkheden/" title="Act! in de Cloud of op kantoor: kies hoe u Act! installeert" class="btn-primary btn">lees verder</a>
										    <a href="demo" title="Laat u adviseren door een Act! productexpert" class="btn-second btn">demo aanvragen</a>
										</div>
									</div>
									<div class="col-sm-4 imagefix hidden-xs"> </div>
								</div>
							</div>
						</div>
					</li>





				</ul>
			</div>
		</div>
