          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/rebokbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/nl-nl/img/reeboklogo.png" alt="reebok sports club logo"></div>

                <blockquote>
                  "Elk jaar schrijven 5000 nieuwe leden zich bij ons in. Zonder Act! was ons dat nooit gelukt."
                </blockquote>
                <a href="testimonials/reebok" title="" class="btn-second-white btn-white">lees verder</a>
              </div>
            </div>
          </div>

       

               <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Information-and-communication Business-Services" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/bg-mannessens-IT-act-crm-customer-story.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/nl-nl/img/ManessenslogoWHITE.png" alt="Manessens logo"></div>

                    <blockquote>
                      "De functionaliteit in Act! kan heel eenvoudig worden aangepast, zodat het pakket precies biedt wat wij nodig hebben..."
                    </blockquote>
                    <a href="testimonials/manessens" title="" class="btn-second-white btn-white">lees verder</a>
                  </div>
                </div>
              </div>

              <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('/en-uk/img/bg-mcj-casings-act-crm-customer-story.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/mcj-casings-logo.png" alt="mcj-casings logo"></div>

                <blockquote>
                  "Dankzij Act! kunnen al onze salesmensen met &eacute;&eacute;n klik alle informatie opvragen over een klant. Zo kunnen we veel..."
                </blockquote>
                <a href="testimonials/mcj-casings" title="Find out more about food manufacturers benefiting from Act!" class="btn-second-white btn-white">lees verder</a>
              </div>
            </div>
          </div>

            <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('/en-uk/img/color-business-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/color-business-centers-white.png" alt="Color Business Centers logo"></div>

                <blockquote>
                  "We zochten naar een systeem dat berekend was op onze toekomstige groei..."
                </blockquote>
                <a href="testimonials/color-business-centers" title="" class="btn-second-white btn-white">lees verder</a>
              </div>
            </div>
          </div>
             