      <footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-2 hidden-xs">
      			
      				<span class="foot_title">Why choose</span>

      				<ul>
      					<li>
      						<a href="why-choose-act" title="Three simple reasons to buy Act!. One easy choice.">Why choose Act!</a>
      					</li>
      					<li>
      						<a href="why-choose-act/cloud-on-premise-deployment" title="Choose the deployment option that's right for your business">Deployment freedom</a>
      					</li>
      					<li>
      						<a href="testimonials-all" title="See what our customers have to say about Act!">Customer testimonials</a>
      					</li>

      				</ul>

      			</div>

      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Products</span>

      				<ul>
      					<li>
      						<a href="products" title="Compare features and benefits between Act! versions">Compare products</a>
      					</li>
      					<li>
      						<a href="products/act-pro" title="Find out more about Act! Pro. Designed for individuals and teams of up to 10 users.">Act! Pro</a>
      					</li>
      					<li>
      						<a href="products/act-premium" title="Find out more about Act! Premium. Designed for individuals and teams of up to 10 or more users.">Act! Premium</a>
      					</li>
      					<li>
      						<a href="products/act-essentials" title="Find out more about Act! Cloud Essentials. Designed for individuals and startups">Act! Cloud Essentials</a>
      					</li>
      					<li>
      						<a href="products/upgrade" title="What's new in the latest release of Act!">What's new in Act! v17</a>
      					</li>
      				</ul>

      			</div>
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Support</span>

      				<ul>
      					<li><a href="support" title="Software support options">Business Care</a></li>
                                                      <li><a href="support/training-opportunities" title="Online or onsite training">Training opportunities</a></li>
                                                      <li><a href="support/obsolescence-policies" title="Supported and unsupported versions">Obsolescence Policy</a></li>
                                                      <li><a href="support/downloads/emea" title="Download software hotfixes, updates and feature packs" >Download Centre</a></li>
                                                      <li><a target="_blank" href="http://www.act.com/support/getting-started/">Resource Centre</a></li>
                                                      <li><a href="http://kb.act.com" target="_blank">Knowledgebase</a></li>
      				</ul>

      			</div>

      			

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title"><a class="footwhite" href="http://www.swiftpage.com/" target="_blank">About Us</a></span>
                              <ul>
                                    
                                          <li>  <a href="http://www.swiftpage.com/en-us/about/legal.shtml" target="_blank">Legals </a></li>
                                          <li>  <a href="support/customer-service/refunds"> Refund Policy</a></li> 
                                          <li>  <a href="waystopay/international"> Payments</a></li>
                              </ul>

                        </div>

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title">Partners</span>
                              <ul>
                                    <li>
                                          <a href="partners-map" title="Find a local partner to help get you up and running effectively and keep you running smoothly">Partner Finder</a>
                                    </li>
                              </ul>

                        </div>

      			<div class=" col-sm-2 social">
				
      				<a href="https://www.youtube.com/user/ActStory" target="_blank" class="social-roll yt">Youtube</a>
      				<a href="https://www.linkedin.com/groups/?gid=1914089" class="social-roll linkd" target="_blank">LinkedIn</a>
      				<a href="https://twitter.com/actstory" class="social-roll twit" target="_blank">Twitter</a>
      				<a href="https://www.facebook.com/actcrm" class="social-roll fb" target="_blank">Facebook</a>

                              <br><br><br>

                            

                              <img src="/en-uk/img/cards.jpg" style="max-width:100%;height:auto" class="hidden-xs"/>  

                              <br><br>   

                               <span class="copyright"> Copyright <strong>Swiftpage ltd 2015 </strong> </span>

                             

      			</div>
      		</div>
      	</div>
      </footer>