      <footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-2 hidden-xs">
      			
      				<span class="foot_title">Why choose</span>

      				<ul>
      					<li>
      						<a href="why-choose-act" title="Three simple reasons to buy Act!. One easy choice.">Why choose Act!</a>
      					</li>
      					<li>
      						<a href="why-choose-act/cloud-on-premise-deployment" title="Choose the deployment option that's right for your business">Deployment freedom</a>
      					</li>
      					<li>
      						<a href="testimonials-all" title="See what our customers have to say about Act!">Customer testimonials</a>
      					</li>

      				</ul>

      			</div>

      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Products</span>

      				<ul>
      					<li>
      						<a href="products" title="Compare features and benefits between Act! versions">Compare products</a>
      					</li>
      					<li>
      						<a href="products/act-pro" title="Find out more about Act! Pro. Designed for individuals and teams of up to 10 users.">Act! Pro</a>
      					</li>
      					<li>
      						<a href="products/act-premium" title="Find out more about Act! Premium. Designed for individuals and teams of up to 10 or more users.">Act! Premium</a>
      					</li>
      					<li>
      						<a href="products/act-essentials" title="Find out more about Act! Essentials. Designed for individuals and startups">Act! Essentials</a>
      					</li>
                                    <li><a href="act-emarketing/" title="Act! emarketing">Act! emarketing</a></li>
      					<li>
      						<a href="products/upgrade" title="What's new in the latest release of Act!">What's new in Act! v17</a>
      					</li>
      				</ul>

      			</div>
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Support</span>

      				<ul>
      					<li><a href="resources" title="Resources">Resources</a></li>
      					<li><a href="support" title="Software support options">Business Care</a></li>
                                                      <li><a href="support/training-opportunities" title="Online or onsite training">Training opportunities</a></li>
                                                      <li><a href="support/obsolescence-policies" title="Supported and unsupported versions">Obsolescence Policy</a></li>
                                                      <li><a href="support/downloads/emea" title="Download software hotfixes, updates and feature packs" >Download Centre</a></li>
                                                      <li><a  href="resources/getting-started/">Getting Started</a></li>
                                                      <li><a href="http://kb.act.com" target="_blank">Knowledgebase</a></li>
                                                       <li><a href="products/system/v18/" >System Requirements</a></li>
                                                      
      				</ul>

      			</div>

      			

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title"><a class="footwhite" href="http://www.swiftpage.com/" target="_blank">About Us</a></span>
                              <ul>
                                    
                                          <li>  <a href="http://www.swiftpage.com/en-us/about/legal.shtml" target="_blank">Legals </a></li>
                                          <li>  <a href="support/customer-service/refunds"> Refund Policy</a></li> 
                                          <li>  <a href="waystopay/international"> Payments</a></li>
                              </ul>

                        </div>

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title">Partners</span>
                              <ul>
                                    <li>
                                          <a href="partners-map" title="Find a local partner to help get you up and running effectively and keep you running smoothly">Partner Finder</a>
                                    </li>
                              </ul>

                        </div>

      			<div class=" col-sm-2 social">
				
      				<a href="https://www.youtube.com/user/ActStory" target="_blank" class="social-roll yt">Youtube</a>
      				<a href="https://www.linkedin.com/groups/?gid=1914089" class="social-roll linkd" target="_blank">LinkedIn</a>
      				<a href="https://twitter.com/actstory" class="social-roll twit" target="_blank">Twitter</a>
      				<a href="https://www.facebook.com/actcrm" class="social-roll fb" target="_blank">Facebook</a>

                              <br><br><br>

                            

                              <img src="/en-uk/img/cards.jpg" style="max-width:100%;height:auto" class="hidden-xs"/>  

                              <br><br>   

                               <span class="copyright"> Copyright <strong>Swiftpage ltd 2015 </strong> </span>

                             

      			</div>
      		</div>
      	</div>
      </footer>
      <script type="text/javascript">
      function elqCreateOptInBanner() {
      if (navigator.appVersion.indexOf('MSIE') != -1) {
      var css = '.cookieBanner {z-index:30; position: absolute; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
      }
      else {
      var css = '.cookieBanner {z-index:30; position: fixed; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
      }
      var style = document.createElement('STYLE');
      style.type = 'text/css';
      if (style.styleSheet) {
      style.styleSheet.cssText = css;
      } else {
      style.appendChild(document.createTextNode(css));
      }
      var head = document.getElementsByTagName('head')[0];
      head.appendChild(style);
      var div = document.createElement('div');
      div.setAttribute('id', 'cookieBannerDiv');
      div.className = 'cookieBanner';
      div.innerHTML = '<div class="cookieBannerText">Our website uses cookies to customise your interactions with us and provide you with a good experience when you browse our website. To find out more about our cookies, please see our <a href="cookie-policy/" style="text-decoration:underline;">cookie policy</a>. By continuing to use our site, you are agreeing to our use of cookies.</div><div class="cookieClose" onclick="document.getElementById(\'cookieBannerDiv\').style.display = \'none\';">x</div>';
      document.body.appendChild(div);

            // Hide alert after 20 seconds
            /*setTimeout(function(){
                  $('.cookieClose').click();
            }, 20000);*/
      }
      </script>