<!--START FIXED NAV WRAPPER-->        
<div class="fixed-wrapper">
  	<div class="container mobile-menu">

		  		<div class="col-md-2 col-lg-1 col-xs-12 col-sm-2 ">
			  		<div class="row">
            		<div class="col-xs-10 col-md-12">
						<a href="/en-uk/"><img src="/en-uk/img/logonew.gif" alt="Act! CRM and Customer Management Logo" class="actlogo"></a>
					</div>
					<div class="trigger-overlay visible-xs col-xs-2" id="mobile_btn">
		        	    <div class="menu_icon"></div>
		        	    <div class="menu_icon_close"></div>
		        	</div>
			  		</div>
				</div>

				<nav class="col-md-6 col-sm-10 col-lg-5 nav-collapse">
					<ul>
						<li><a href="why-choose-act" title="Three simple reasons to buy Act!. One easy choice.">Why choose&nbsp;&nbsp;<span class="down_arrow"></span></a>
							   <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="why-choose-act" title="Three simple reasons to buy Act!. One easy choice.">Why choose Act!</a></li>
					  		 	<li><a href="why-choose-act/cloud-on-premise-deployment" title="Choose the deployment option that's right for your business">Deployment freedom</a></li>
								<li><a href="testimonials-all" title="See what our customers have to say about Act!">Customer testimonials</a></li>
					  		</ul>
						</li>
						<li><a href="products" title="Compare features and benefits between Act! versions">Products&nbsp;&nbsp;<span class="down_arrow"></span></a>
                            <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="products" title="Compare features and benefits between Act! versions">Compare products</a></li>
					  		 	<li><a href="products/act-pro" title="Find out more about Act! Pro. Designed for individuals and teams of up to 10 users.">Act! Pro</a></li>
					  		 	<li><a href="products/act-premium" title="Find out more about Act! Premium. Designed for individuals and teams of up to 10 or more users.">Act! Premium</a></li>
								<li><a href="products/act-essentials" title="Find out more about Act! Essentials. Designed for individuals and startups">Act! Essentials</a></li>
								<li><a href="act-emarketing/" title="Act! emarketing">Act! emarketing</a></li>
								

					  		 	<li><a href="products/upgrade" title="What's new in the latest release of Act!">What's new in Act! v17</a></li>
					  		</ul>
					  	</li>
					  	<li><a href="resources" title="Software support options">Support&nbsp;&nbsp;<span class="down_arrow"></span></a>
								<ul>
									<li><a href="resources" title="Resources">Resources</a></li>
									<li><a href="support" title="Software support options">Business Care</a></li>
									<li><a href="support/training-opportunities" title="Online or onsite training">Training opportunities</a></li>
									<li><a href="support/obsolescence-policies" title="Supported and unsupported versions">Obsolescence Policy</a></li>
									<li><a href="support/downloads/emea" title="Download software hotfixes, updates and feature packs" >Download Centre</a></li>
									<li><a href="resources/getting-started/">Getting Started</a></li>
									<li><a href="http://kb.act.com" target="_blank">Knowledgebase</a></li>
								</ul>
						</li>
					  	<li><a href="partners-map" title="Find a local partner to help get you up and running effectively and keep you running smoothly">Partners</a></li>
                		<li><a href="http://community.act.com/" target="_blank">Community</a></li>
				  		<!--<li><a href="http://www.swiftpage.com/en-gb/" target="_blank">About Us</a></li>-->
					</ul>
					<br style="clear:both">
				</nav>
				
				<div class="col-md-2 contact_no hidden-xs hidden-md hidden-sm">
					<div class="header-countries">
						UK: <strong>0845 268 0220</strong><br /> 
						Ireland: <strong>0766 801 364</strong><br />
						South Africa: <strong>0105 003 672</strong>
					</div>
				</div>
				
				<div class="col-md-3 col-sm-8 tl_links hidden-xs">
					<a href="contact-us" title="Get in touch by telephone, email or send us a message" class="btn btn-second">Contact us</a>
					<a href="test-drive" title="Online access to Act! desktop software through your web browser" class="btn btn-second">Test drive</a> 
				</div>
				<div class="col-sm-1">
					<nav class="langmenu">
						<ul>
							<li >Language: <strong class="lang_menu">English <span class="down_arrow"></span></strong>
								<ul>
									<li><a href="http://www.act.com/de-de/" lang="de" hreflang="de" title="Act! CRM Software">Deutsch</a></li>
									<li><a href="http://www.act.com/fr-fr/" lang="fr" hreflang="fr" title="Act! Logiciel CRM">Fran&#231;ais</a></li>
									<li><a href="http://www.act.com/fr-ca/" lang="fr" hreflang="fr" title="Act! Logiciel CRM">Fran&#231;ais Canada</a></li>
									<li><a href="http://www.act.com/nl-nl/" lang="nl" hreflang="nl" title="Act! CRM Software">Nederlands</a></li>
									<li><a href="http://www.act.com/?regLang=en-US" lang="en-us" hreflang="en-us" title="Act! CRM Software">U.S. English</a></li>
								</ul>
							</li>
						</ul>
					</nav>
				</div>

    </div>
</div>
<div class="spacer"></div>
<!--END FIXED WRAPPER-->