<!--START FIXED NAV WRAPPER-->        
<div class="fixed-wrapper">
  <!--START ORANGE TOP BAR-->
        <div class="topbar hidden-xs">
          	<div class="container">
              	<div class="col-sm-4 tl_links">
                  	<a href="test-drive" title="Online access to Act! desktop software through your web browser"> <strong>Test drive &gt;</strong> </a> 
				  	<a href="contact-us" title="Get in touch by telephone, email or send us a message"><strong>Contact us &gt;</strong></a>
                </div>
				<div class="col-sm-6 ">
                		<div class="hidden-sm ">
	                		UK: <strong>0845 268 0220</strong> 
	                		Ireland: <strong>0766 801 364</strong> 
	                		South Africa: <strong>0105 003 672</strong>
                		</div>
              	</div>
			  	<div class="col-sm-2">
                		<nav>
               			<ul>
			   			 	<li >Language: <strong class="lang_menu">English <span class="down_arrow hidden-sm"></span></strong>
			   			 		<ul>
			   			 			<li><a href="http://www.act.com/de-de/" lang="de" hreflang="de" title="Act! CRM Software">Deutsch</a></li>
			   			 			<li><a href="http://www.act.com/fr-fr/" lang="fr" hreflang="fr" title="Act! Logiciel CRM">Fran&#231;ais</a></li>
			   			 			<li><a href="http://act.com/?regLang=en-US" lang="en-us" hreflang="en-us" title="Act! CRM Software">English (U.S.)</a></li>
			   			 		</ul>
			   			 	</li>
			   			</ul>
                		</nav>
              	</div>
            </div>
         </div>
  <!--END ORANGE TOP BAR-->

  <!--START MAIN NAVIGATION (WHITE)-->
        <div class="container">
          	<div class="row">
            	<div class="col-sm-2 col-xs-12 mobile-menu">
            		<div class="row">
            			<div class="col-xs-10">
							<a href="/en-uk/"><img src="/en-uk/img/act-crm-and-customer-management-logo.gif" alt="Act! CRM and Customer Management Logo" class="actlogo"></a>
						</div>
		                <div class="trigger-overlay visible-xs col-xs-2" id="mobile_btn">
		                  	<div class="menu_icon"></div>
		                  	<div class="menu_icon_close"></div>
		                </div>
		            </div>
	            </div>
				<nav class="col-sm-10 nav-collapse">
					<ul>
						<li><a href="why-choose-act" title="Three simple reasons to buy Act!. One easy choice.">Why choose</a>
							   <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="why-choose-act" title="Three simple reasons to buy Act!. One easy choice.">Why choose Act!</a></li>
					  		 	<li><a href="why-choose-act/cloud-on-premise-deployment" title="Choose the deployment option that's right for your business">Deployment freedom</a></li>
								<li><a href="testimonials-all" title="See what our customers have to say about Act!">Customer testimonials</a></li>
								
								
								 
					  		</ul>
						</li>
						<li><a href="products" title="Compare features and benefits between Act! versions">Products</a>
                            <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="products" title="Compare features and benefits between Act! versions">Compare products</a></li>
					  		 	<li><a href="products/act-pro" title="Find out more about Act! Pro. Designed for individuals and teams of up to 10 users.">Act! Pro</a></li>
					  		 	<li><a href="products/act-premium" title="Find out more about Act! Premium. Designed for individuals and teams of up to 10 or more users.">Act! Premium</a></li>
								<li><a href="products/act-essentials" title="Find out more about Act! Cloud Essentials. Designed for individuals and startups">Act! Cloud Essentials</a></li>
					  		 	<li><a href="products/upgrade" title="What's new in the latest release of Act!">What's new in Act! v17</a></li>
					  		</ul>
					  	</li>
					  	<li><a href="support" title="Software support options">Support</a>
						
								<ul>
									<li><a href="support" title="Software support options">Business Care</a></li>
									<li><a href="support/training-opportunities" title="Online or onsite training">Training opportunities</a></li>
									<li><a href="support/obsolescence-policies" title="Supported and unsupported versions">Obsolescence Policy</a></li>
									<li><a href="support/downloads/emea" title="Download software hotfixes, updates and feature packs" >Download Centre</a></li>
									<li><a target="_blank" href="http://www.act.com/support/getting-started/">Resource Centre</a></li>
									<li><a href="http://kb.act.com" target="_blank">Knowledgebase</a></li>

								</ul>
						</li>
					  	<li><a href="partners-map" title="Find a local partner to help get you up and running effectively and keep you running smoothly">Partners</a></li>
                		<li><a href="http://community.act.com/" target="_blank">Community</a></li>
				  		<li><a href="http://www.swiftpage.com/en-gb/" target="_blank">About Us</a></li>
                		<li><a href="contact-us" title="Get in touch by telephone, email or send us a message">Contact</a></li>
					</ul>
					<br style="clear:both">
				</nav>

				
			</div>
        </div>
  <!--END MAIN NAVIGATION-->
</div>
<div class="spacer"></div>
<!--END FIXED WRAPPER-->