        <div class="slider-container">
          	<div class="slider ">
            		<ul>
					<li class="cta">
						<div class="slider-bg">
							<img src="/en-uk/img/business-woman-satisfied-using-act.jpg" alt="Satisfied user of Act! Contact Management" />
						</div>

						<div class="slider-overlay">
							<div class="container ">
								<div class="row section">
								  	<div class="col-sm-8 col-left bottom mb-center ">
								    		<h1 class="large_strapline_home semibold">
								    		<strong>Act! is the #1 </strong>best-selling Contact &amp; Customer Manager </h1>
										 <div class="btn-bottom">
								      		<a target="_blank" class="btn-primary btn buy-popup">buy now</a>
								      		<a href="test-drive" title="Online access to Act! desktop software through your web browser" class="btn-second btn">test drive</a>
								      		<a href="demo" title="Request a demonstration of Act!" class="btn-second btn">request demo</a>
									  	</div>
									 </div>
									 <div class="col-sm-4 imagefix hidden-xs">

                      				 </div>
								</div>
							</div>
						</div>
					</li>

					<li class="cta">
						<div class="slider-bg">
							<img src="/en-uk/img/marketing-team-using-act.jpg" alt="Marketing team meeting using Act!" />
						</div>

						<div class="slider-overlay">
							<div class="container ">
								<div class="row section">
								  	<div class="col-sm-7 col-left bottom mb-center col-xs-12">
								    		<span class="large_strapline_home semibold"><strong>Introducing new Act! Cloud Essentials,</strong> so easy to get along with</span>
									 <div class="btn-bottom">
								      		<a href="https://mycloud.act.com/#/account/billing" target="_blank" class="btn-primary btn">buy now</a>
								      		<a target="_blank" href="https://mycloud.act.com/signup/" class="btn-second btn">free trial</a>
									  	</div>
									 </div>
									  <div class="col-sm-4 imagefix hidden-xs">

                      				 </div>
								</div>
							</div>
						</div>
					</li>





					<li class="cta">
						<div class="slider-bg">
							<img src="/en-uk/img/act-for-reebok-sports-club.jpg" alt="Reebok sports club Act! CRM customer story" />
						</div>
					<div class="slider-overlay">
						<div class="container ">
							<div class="row section">
							  	<div class="col-sm-7  white bottom col-left mb-center col-xs-12">
							    		<span class="large_strapline_home semibold"> "Act! The ultimate fitness tool for sales" </span>
							   <img src="/en-uk/img/reebok.png" alt="" width="160" class="hidden-xs">
							   <br> <br>
									 <div class="btn-bottom white">
							      		<a href="testimonials/reebok" title="Find out more about health clubs benefiting from using Act!" class="btn-primary btn">read more</a>
							      		<a href="testimonials-all" title="See what our customers have to say about Act!" class="btn-second btn">view all testimonials</a>
								  	</div>
								 </div>
								  <div class="col-sm-4 imagefix hidden-xs"></div>
							</div>
						</div>
						</div>
					</li>

					<li class="cta">
						<div class="slider-bg playVideo">
							<img src="/en-uk/img/video-sales-using-act-contact-management.jpg" alt="Video: salesman using Act! Contact Management software" />
						</div>

						<div class="slider-overlay playVideo">
							<div class="container ">
								<div class="row section ">
								  	<div class="col-sm-8 col-left bottom mb-center col-xs-12">
								    	<span class="large_strapline_home semibold playVideo"><strong>Find out how</strong><br>Act! can help your business</span>
										<div class="btn-bottom">
									    	<a  class="playVideo btn-primary btn">Watch now</a>
										</div>
									</div>
									<div class="col-sm-4 imagefix hidden-xs"> </div>
								</div>
							</div>
						</div>
					</li>




					<li class="cta">
						<div class="slider-bg">
							<img src="/en-uk/img/field-sales-using-act.jpg" alt="One member of a sales team using Act!" />
						</div>

						<div class="slider-overlay">
							<div class="container ">
								<div class="row">
								  	<div class="col-sm-8 bottom col-left mb-center col-xs-12">
									    <span class="large_strapline_home semibold"><strong>On-premises<br>or Cloud:</strong><br>It's your choice</span>
										<div class="btn-bottom">
										    <a href="why-choose-act/cloud-on-premise-deployment" title="Choose the deployment option that's right for your business" class="btn-primary btn">find out more</a>
										    <a href="test-drive" title="Online access to Act! desktop software through your web browser" class="btn-second btn">test drive</a>
										    <a href="demo" title="Request a demonstration of Act!" class="btn-second btn">request demo</a>
										</div>
									</div>
									<div class="col-sm-4 imagefix hidden-xs"> </div>
								</div>
							</div>
						</div>
					</li>





				</ul>
			</div>
		</div>
