          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/srtbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/srtlogo.png" alt="SRT logo"></div>
                <blockquote>
                  "When customers bring in images of hairstyles, I scan them and add them to their file to keep a..."
                </blockquote>
                <a href="testimonials/srt" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>


         <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Wholesale-and-Retail" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/thescalepeoplebg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/thescalepeoplelogo.png" alt="The Scale People logo"></div>

                <blockquote>
                  "In terms of efficiency we've been able to improve productivity by at least 30% using Act!..."
                </blockquote>
                <a href="testimonials/the-scale-people" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>


          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Health-and-Social-Work" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/occuvaxbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/occuvaxlogo-white.png" alt="occuvax logo"></div>

                <blockquote>
                  "OccuVAX now has the powerful CRM tool it needed and which was actually in its hands all along...."
                </blockquote>
                <a href="testimonials/occuvax" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>


          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Agriculture-Forestry-and-Fishing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/onefourgroupbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/onefourlogo.png" alt="One Four Group logo"></div>

                <blockquote>
                  "We only get to meet up in one place three or four times a year, but Act! brings the sales team together every day"
                </blockquote>
                <a href="testimonials/one-four-group/" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>




          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Sports-leisure-and-entertainment" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/rebokbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/reeboklogo.png" alt="reebok sports club logo"></div>

                <blockquote>
                  "I know that if we didn't have Act!, we wouldn't come close to achieving the 5,000 new memberships..."
                </blockquote>
                <a href="testimonials/reebok" title="Find out more about health clubs benefiting from using Act!" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>


          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('/en-uk/img/bg-mcj-casings-act-crm-customer-story.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/mcj-casings-logo.png" alt="mcj-casings logo"></div>

                <blockquote>
                  "With Act! all members of our sales team can find out everything they need to know about a customer..."
                </blockquote>
                <a href="testimonials/mcj-casings" title="Find out more about food manufacturers benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>
        
            <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Information-and-communication" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/bg-act-for-startup-limefresh-media.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/limefresh-logo.png" alt="limefresh logo"></div>

                <blockquote>
                  "On a daily basis, Act! lets us connect with existing and potential advertisers at just the right time"
                </blockquote>
                <a href="testimonials/limefresh" title="Find out more about service companies benefiting from Act!" title="Find out more about publishers and startups benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Wholesale-and-Retail" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/bg-connect-vending-customer-story.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/connectvendinglogoWHITE.png" alt="connect vending logo"></div>

                    <blockquote>
                     "By using Act! more fully, we're able to turn more of our cold contacts into sales..."
                    </blockquote>
                    <a href="testimonials/connect-vending" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

               <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Information-and-communication Business-Services" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/bg-mannessens-IT-act-crm-customer-story.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/ManessenslogoWHITE.png" alt="Manessens logo"></div>

                    <blockquote>
                      "Act! gives us the opportunity to personalise its features so we can tailor it to our exact needs"
                    </blockquote>
                    <a href="testimonials/manessens" title="Find out more about IT consultants benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Sports-leisure-and-entertainment" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/rayburns-bg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/rayburns-logo.png" alt="Rayburns logo"></div>

                    <blockquote>
                     "It's quick, slick and cost-effective and has taken our productivity to a whole different level."
                    </blockquote>
                    <a href="testimonials/rayburns" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

               <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Health-and-Social-Work" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/morningside-bg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/morningside-logo.png" alt="Morningside logo"></div>

                    <blockquote>
                      "Act! gives us the information we need quickly and accurately..."
                    </blockquote>
                    <a href="testimonials/morningside" title="Find out more about IT consultants benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

                  <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/mvmsmallbg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/mvmlogo.png" alt="Mvm logo"></div>

                    <blockquote>
                      "Act! offers a total service package that has helped us grow..."
                    </blockquote>
                    <a href="testimonials/mvm" title="Find out more about IT consultants benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

                  <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/schochsmallbg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/schochlogowhite.png" alt="Schoch logo"></div>

                    <blockquote>
                      "The great strength of Act! is its incredible flexibility when it comes..."
                    </blockquote>
                    <a href="testimonials/schoch-werkhaus" title="Find out more about Schoch benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

                 <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/color-business-bg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/color-business-centers-white.png" alt="Schoch logo"></div>

                    <blockquote>
                      "It's very satisfying to see our very own, customised CRM and sales support system evolving..."
                    </blockquote>
                    <a href="testimonials/color-business-centers" title="" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

