          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/rebokbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/reeboklogo.png" alt="reebok sports club logo"></div>

                <blockquote>
                  "I know that if we didn't have Act!, we wouldn't come close to achieving the 5,000 new memberships..."
                </blockquote>
                <a href="testimonials/reebok" title="Find out more about health clubs benefiting from using Act!" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('/en-uk/img/bg-mcj-casings-act-crm-customer-story.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/mcj-casings-logo.png" alt="mcj-casings logo"></div>

                <blockquote>
                  "With Act! all members of our sales team can find out everything they need to know about a customer..."
                </blockquote>
                <a href="testimonials/mcj-casings" title="Find out more about food manufacturers benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/bg-corkers-crisps-act-customer-story.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/corkers-logo.png" alt="corkers logo"></div>

                <blockquote>
                  "Recently, I wanted to track which prospects had been sent samples. Swiftpage helped me customise ..."
                </blockquote>
                <a href="testimonials/corkers" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>
            <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="information" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('/en-uk/img/bg-act-for-startup-limefresh-media.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="/en-uk/img/limefresh-logo.png" alt="limefresh logo"></div>

                <blockquote>
                  "On a daily basis, Act! lets us connect with existing and potential advertisers at just the right time"
                </blockquote>
                <a href="testimonials/limefresh" title="Find out more about service companies benefiting from Act!" title="Find out more about publishers and startups benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/bg-connect-vending-customer-story.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/connectvendinglogoWHITE.png" alt="connect vending logo"></div>

                    <blockquote>
                     "By using Act! more fully, we're able to turn more of our cold contacts into sales..."
                    </blockquote>
                    <a href="testimonials/connect-vending" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

               <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Informationstechnologie" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/bg-mannessens-IT-act-crm-customer-story.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/ManessenslogoWHITE.png" alt="Manessens logo"></div>

                    <blockquote>
                      "Act! gives us the opportunity to personalise its features so we can tailor it to our exact needs"
                    </blockquote>
                    <a href="testimonials/manessens" title="Find out more about IT consultants benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/rayburns-bg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/rayburns-logo.png" alt="Rayburns logo"></div>

                    <blockquote>
                     "It's quick, slick and cost-effective and has taken our productivity to a whole different level."
                    </blockquote>
                    <a href="testimonials/rayburns" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>

               <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Informationstechnologie" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/morningside-bg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/morningside-logo.png" alt="Morningside logo"></div>

                    <blockquote>
                      "Act! gives us the information we need quickly and accurately..."
                    </blockquote>
                    <a href="testimonials/morningside" title="Find out more about IT consultants benefiting from Act!" class="btn-second-white btn-white">Find out more</a>
                  </div>
                </div>
              </div>