      <footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-2 hidden-xs">
      			
      				<span class="foot_title">Vorteile &amp; Nutzen </span>

      				<ul>
      					<li>
      						<a href="warum-act" title="Vorteile und Nutzen der Kundenmanagement Software Act!">Warum Act!?</a>
      					</li>
      					<li>
      						<a href="kundenreferenzen" title="Unternehmen, die die CRM Software Act! bereits nutzen">Kundenreferenzen</a>
      					</li>

      				</ul>

      			</div>

      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Produkte</span>

      				<ul>
      					<li>
      						<a href="produkte" title="Die Act! Software Produkte im Überblick">Produkte vergleichen</a>
      					</li>
      					<li>
      						<a href="produkte/act-pro" title="CRM Software Version Act! Pro">Act! Pro</a>
      					</li>
      					<li>
      						<a href="produkte/act-premium" title="CRM Software Version Act! Premium">Act! Premium</a>
      					</li>
                                    <li><a href="act-emarketing/" title="Act! emarketing">Act! emarketing</a></li>
      					<li>
      						<a href="produkte/was-ist-neu" title="Das ist neu bei der aktuellen Act! Software Version">Act! v17: Was ist neu?</a>
      					</li>
      				</ul>

      			</div>
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Service &amp; Support</span>

      				<ul>
      					<li>
      						<a href="support/wartungsvertraege" title="Wartungsverträge für CRM Software Act!">Wartungsverträge</a>
      					</li>
      					<li>
      						<a href="support/obsoleszenz-regelung" title="Obsoleszenz Regelungen für Act!">Obsoleszenz-Regelung</a>
      					</li>
      					<li>
      						<a href="support/downloads" tiltle="Downloads, Updates und Hotfixes zur Software Act!" >Download Centre</a>
      					</li>
                                    <li>
                                          <a href="http://kb-de.swiftpage.com/" target="_blank">Knowledgebase</a>
                                    </li>
      				</ul>

      			</div>

      			

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title"><a class="footwhite" href="http://www.swiftpage.com/de-de/" target="_blank">&Uuml;ber uns</a></span>
                              <ul>
                                    
                                          <li>  <a href="http://www.swiftpage.com/en-us/about/legal.shtml" target="_blank">Richtlinien</a></li>
                                          <li>  <a href="zahlungsmoeglichkeiten">Zahlungen</a></li> 
                                          <li>  <a href="impressum">Impressum</a></li> 
                                          <li><a href="produkte/Systemvoraussetzungen/">Systemvoraussetzungen</a></li>
                              </ul>

                        </div>

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title">Partner</span>
                              <ul>
                                    <li>
                                          <a href="partner-finden" title="Finden Sie einen Act! Partner in Ihrer Nähe">Partner finden</a>
                                    </li>
                              </ul>

                        </div>

      			<div class=" col-sm-2 social">
				
      				<a href="https://www.youtube.com/user/ActStory" target="_blank" class="social-roll yt">Youtube</a>
      				<a href="https://www.linkedin.com/groups/?gid=1914089" class="social-roll linkd" target="_blank">LinkedIn</a>
      				<a href="https://twitter.com/actstory" class="social-roll twit" target="_blank">Twitter</a>
      				<a href="https://www.facebook.com/actcrm" class="social-roll fb" target="_blank">Facebook</a>

                              <br class="hidden-xs"><br class="hidden-xs"><br class="hidden-xs">

                            

                              <img src="img/cards.jpg" style="max-width:100%;height:auto" class="hidden-xs"/>

                              <br><br>     

                               <span class="copyright"> Copyright <strong>Swiftpage ltd 2015 </strong> </span>

                             
      			</div>
      		</div>
      	</div>
      </footer>
      <script type="text/javascript">
      function elqCreateOptInBanner() {
      if (navigator.appVersion.indexOf('MSIE') != -1) {
      var css = '.cookieBanner {z-index:30; position: absolute; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
      }
      else {
      var css = '.cookieBanner {z-index:30; position: fixed; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
      }
      var style = document.createElement('STYLE');
      style.type = 'text/css';
      if (style.styleSheet) {
      style.styleSheet.cssText = css;
      } else {
      style.appendChild(document.createTextNode(css));
      }
      var head = document.getElementsByTagName('head')[0];
      head.appendChild(style);
      var div = document.createElement('div');
      div.setAttribute('id', 'cookieBannerDiv');
      div.className = 'cookieBanner';
      div.innerHTML = '<div class="cookieBannerText">Unsere Webseite nutzt Cookies, um Ihre Interaktionen mit uns besser auf Sie abstimmen zu k&ouml;nnen und Ihnen so eine besseres Surf-Erlebnis auf unserer Webseite bieten zu k&ouml;nnen. F&uuml;r mehr Informationen, &uuml;berpr&uuml;fen Sie bitte unsere <a href="cookie-richtlinien/" style="text-decoration:underline;">Cookie Richtlinien</a>. Indem Sie mit dem Nutzen unserer Website fortfahren, erkl&auml;ren Sie sich mit der Verwendung unserer Cookies einverstanden.</div><div class="cookieClose" onclick="document.getElementById(\'cookieBannerDiv\').style.display = \'none\';">x</div>';
      document.body.appendChild(div);

            // Hide alert after 20 seconds
            /*setTimeout(function(){
                  $('.cookieClose').click();
            }, 20000);*/
      }
      </script>