<!--START FIXED NAV WRAPPER-->        
<div class="fixed-wrapper">
  	<div class="container mobile-menu">

		  		<div class="col-md-2 col-lg-1 col-xs-12 col-sm-2 ">
			  		<div class="row">
            		<div class="col-xs-10 col-md-12">
						<a href="/de-de/"><img src="/en-uk/img/logonew.gif" alt="Act! CRM and Customer Management Logo" class="actlogo"></a>
					</div>
					<div class="trigger-overlay visible-xs col-xs-2" id="mobile_btn">
		        	    <div class="menu_icon"></div>
		        	    <div class="menu_icon_close"></div>
		        	</div>
			  		</div>
				</div>

				<nav class="col-md-6 col-sm-10 col-lg-5 nav-collapse">
					<ul>
						<li><a href="warum-act" title="Vorteile und Nutzen der Kundenmanagement Software Act!">Vorteile &amp; Nutzen &nbsp;&nbsp;<span class="down_arrow"></span></a>
							   <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="warum-act" title="Vorteile und Nutzen der Kundenmanagement Software Act!">Warum Act!?</a></li>
								<li><a href="kundenreferenzen" title="Unternehmen, die die CRM Software Act! bereits nutzen">Kundenreferenzen</a></li>
								
								
								 
					  		</ul>
						</li>
						<li><a href="produkte" title="Die Act! Software Produkte im Überblick">Produkte &nbsp;&nbsp;<span class="down_arrow"></span></a>
                            <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="produkte" title="Die Act! Software Produkte im Überblick">Produkte vergleichen</a></li>
					  		 	<li><a href="produkte/act-pro" title="CRM Software Version Act! Pro">Act! Pro</a></li>
					  		 	<li><a href="produkte/act-premium" title="CRM Software Version Act! Premium">Act! Premium</a></li>
								<!--<li><a href="act-productpage-mobility">Mobile Lösungen</a></li>-->
								<li><a href="act-emarketing/" title="Act! emarketing">Act! emarketing</a></li>
					  		 	<li><a href="produkte/was-ist-neu" title="Das ist neu bei der aktuellen Act! Software Version">Act! v17: Was ist neu?</a></li>
					  		</ul>
					  	</li>
					  	<li><a href="support/wartungsvertraege" title="Wartungsverträge für CRM Software Act!">Service &amp; Support &nbsp;&nbsp;<span class="down_arrow"></span></a>
						
								<ul>
									<li><a href="support/wartungsvertraege" title="Wartungsverträge für CRM Software Act!">Wartungsverträge</a></li>
									<li><a href="support/obsoleszenz-regelung" title="Obsoleszenz Regelungen für Act!">Obsoleszenz-Regelung</a></li>
									<li><a href="support/downloads" tiltle="Downloads, Updates und Hotfixes zur Software Act!" >Download Centre</a></li>
									<li><a href="http://kb-de.swiftpage.com/" target="_blank">Knowledgebase</a></li>

								</ul>
						</li>
					  	<li><a href="partner-finden" title="Finden Sie einen Act! Partner in Ihrer Nähe">Partner</a></li>
					</ul>
					<br style="clear:both">
				</nav>
				
				<div class="col-md-2 contact_no hidden-xs hidden-md hidden-sm">
					<div class="header-countries">
								Deutschland:<br> <strong>069 643 508 433</strong> <br>
	                		Schweiz: <br>	 <strong>043 508 2364</strong> 
					</div>
				</div>
				
				<div class="col-md-3 col-sm-8 tl_links hidden-xs">
					<a href="kontakt" title="Kontaktieren Sie das Act! Team" class="btn btn-second">Kontakt</a>
					<a href="kostenlos-testen" title="CRM Software Act! kostenlos testen" class="btn btn-second">Gratis testen</a> 
				</div>
				<div class="col-sm-1">
					<nav class="langmenu">
						<ul>
							<li >Sprache: <strong class="lang_menu">Deutsch <span class="down_arrow "></span></strong>
								<ul>
								<li><a href="http://www.act.com/en-uk/" lang="en" hreflang="en" title="Act! CRM Software">English</a></li>
			   			 			<li><a href="http://www.act.com/fr-fr/" lang="fr" hreflang="fr" title="Act! Logiciel CRM">Fran&#231;ais</a></li>
									<li><a href="http://www.act.com/fr-ca/" lang="fr" hreflang="fr" title="Act! Logiciel CRM">Fran&#231;ais Canada</a></li>
			   			 			<li><a href="http://www.act.com/nl-nl/" lang="nl" hreflang="nl" title="Act! CRM Software">Nederlands</a></li>
			   			 			<li><a href="http://www.act.com/?regLang=en-US" lang="en-us" hreflang="en-us" title="Act! CRM Software">U.S. English</a></li>
							</li>
						</ul>
					</nav>
				</div>

    </div>
</div>
<div class="spacer"></div>