        <div class="slider-container">
          	<div class="slider ">
            		<ul>
					<li class="cta">
						<div class="slider-bg">
							<img src="img/Geschaftsfrau-ist-glucklich-mit-act.jpg" alt="Geschäftsfrau ist glücklich mit Act!" />
						</div>

						<div class="slider-overlay">
							<div class="container ">
								<div class="row section">
								  	<div class="col-sm-8 col-left bottom mb-center">
								    		<h1 class="large_strapline_home semibold"><strong>Act! - professionelles </strong> Kontakt - und Kundenmanagement</h1>
										 <div class="btn-bottom">
								      		<a target="_blank" href="http://store.act.com/app/site/backend/intl/additemtocart.nl?buyid=2998&qty=1&selcurrency=4&selsubsidiary=7&selshopperlanguage=de_DE" class="btn-primary btn">Jetzt kaufen</a>
								      		<a href="kostenlos-testen" title="CRM Software Act! kostenlos testen" class="btn-second btn">Jetzt kostenlos testen</a>
								      		<a href="demo-anfordern" title="Fordern Sie eine Demo der CRM Software Act! an" class="btn-second btn">Demo anfordern</a>
									  	</div>
									 </div>
									 <div class="col-sm-3 imagefix hidden-xs">

                      				 </div>
								</div>
							</div>
						</div>
					</li>


					<li class="cta">
						<div class="slider-bg">
							<img src="img/reebok-nutzt-act.jpg" />
						</div>
					<div class="slider-overlay">
						<div class="container ">
							<div class="row section">
							  	<div class="col-sm-8 col-lg-8 col-md-7 col-left white bottom col-left mb-center">
							    		<span class="large_strapline_home semibold">Act! ist das ultimative „Fitnesstool“ für den Vertrieb</span>
							   <img src="img/reebok.png" alt="reebok sports club logo" width="160" style="display:none">
							   <br> <br>
									 <div class="btn-bottom white">
							      		<a href="kundenreferenzen/reebok" title="Act! Referenzkunde Reebok" class="btn-primary btn">mehr Infos</a>
							      		<a href="kundenreferenzen" title="Unternehmen, die die CRM Software Act! bereits nutzen" class="btn-second btn">Alle Kundenreferenzen</a>
								  	</div>
								 </div>
								  <div class="col-sm-2 imagefix hidden-xs"></div>
							</div>
						</div>
						</div>
					</li>

					</li>




					<li class="cta">
						<div class="slider-bg playVideo">
							<img src="img/video-ansehen-mehr-erfahren.jpg" alt="Sehen Sie sich das Video an und erfahren Sie mehr zur Software" />
						</div>

						<div class="slider-overlay playVideo">
							<div class="container ">
								<div class="row section">
								  	<div class="col-sm-12 bottom col-left mb-center">
								  		<div class="row">
									  		<div class="col-sm-7">
									    		<span class="large_strapline_home semibold playVideo">So wird Ihr Unternehmen noch erfolgreicher - mit Act!</span>
									    	</div>
									    </div>
										<div class="btn-bottom">
										    <a class="playVideo btn-primary btn">Video ansehen</a>
										</div>
									 </div>
									  <div class="col-sm-4 imagefix hidden-xs"> </div>
								</div>
							</div>
						</div>
					</li>





				</ul>
			</div>
		</div>
