          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/srtbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/srtlogo.png" alt="SRT logo"></div>

                <blockquote>
                  „Ich schätze die Benutzerfreundlichkeit von Act!, die Stabilität und die flexiblen Optionen.“
                </blockquote>
                <a href="kundenreferenzen/srt" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
          
         <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Wholesale-and-Retail" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/thescalepeoplebg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/thescalepeoplelogo.png" alt="The Scale People logo"></div>

                <blockquote>
                  „Act! hat unsere Produktivit&auml;t um mindestens 30 Prozent gesteigert. Unsere Mitbewerber...“
                </blockquote>
                <a href="kundenreferenzen/the-scale-people"  class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
          
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Health-and-Social-Work" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/occuvaxbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/occuvaxlogo-white.png" alt="Occuvax logo"></div>

                <blockquote>
                  „OccuVAX verfu&#776;gt nun u&#776;ber das leistungsstarke CRM-Tool, welches das Unternehmen brauchte...“
                </blockquote>
                <a href="kundenreferenzen/occuvax"  class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
          
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Agriculture-Forestry-and-Fishing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/onefourgroupbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/onefourlogo.png" alt="1,4 Group logo"></div>

                <blockquote>
                  „Auch wenn wir uns nur drei- oder viermal im Jahr pers&ouml;nlich treffen...“
                </blockquote>
                <a href="kundenreferenzen/one-four-group" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
         
         
         
         
          
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Sports-leisure-and-entertainment" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/rebokbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/reeboklogo.png" alt="reebok sports club logo"></div>

                <blockquote>
                  „Ohne Act! würden wir es nicht schaffen, jedes Jahr 5000 neue Mitglieder zu gewinnen“
                </blockquote>
                <a href="kundenreferenzen/reebok" title="Act! Referenzkunde Reebok" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
          
          
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('img/bg-referenzkunde-crm-software-fleischwaren.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/mcj-casings-logo.png" alt="mcj-casings logo"></div>

                <blockquote>
                  „Dank Act! können wir unsere Verkaufsgespräche viel besser planen!“
                </blockquote>
                <a href="kundenreferenzen/mcj-casings" title="Act! Referenzkunde MCJ Casings" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
         
            <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Information-and-communication" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/limefresh-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/limefresh-logo.png" alt="limefresh logo"></div>

                <blockquote>
                  „Act! ermöglicht uns, Anzeigenkunden genau zum richtigen Zeitpunkt anzusprechen.“
                </blockquote>
                <a href="kundenreferenzen/limefresh" title="Act! Referenzkunde Limefresh" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>


      <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Wholesale-and-Retail" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/man-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/connectvendinglogoWHITE.png" alt="connect vending logo"></div>

                <blockquote>
                 „Dank Act! konnten wir den Aufbau unserer internen Systeme verbessern..."
                </blockquote>
                <a href="kundenreferenzen/connect-vending" title="Act! Referenzkunde Connect Vendig" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Information-and-communication Business-Services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/bg-referenzkunde-crm-software-automaten.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/ManessenslogoWHITE.png" alt="manessens logo"></div>

                <blockquote>
                  „Unsere Wahl fiel auf das Kontaktmanagementsystem Act!, da wir mit dieser Software die M&ouml;..."
                </blockquote>
                <a href="kundenreferenzen/manessens" title="Act! Referenzkunde Manessens" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Sports-leisure-and-entertainment" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/rayburns-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/rayburns-logo.png" alt="Rayburns logo"></div>

                <blockquote>
                 „Die Software ist schnell, professionell und kostengu&#776;nstig und hat unsere Produktivit&auml;t auf eine neue Stufe gehoben"
                </blockquote>
                <a href="kundenreferenzen/rayburns" title="Act! Referenzkunde Rayburns" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Health-and-Social-Work" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/morningside-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/morningside-logo.png" alt="Morningside logo"></div>

                <blockquote>
                  „Act! stellt uns die ben&ouml;tigten Informationen schnell und pr&auml;zise zur Verfu&#776;gung ..."
                </blockquote>
                <a href="kundenreferenzen/morningside" title="Act! Referenzkunde Morningside" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>


                  <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/mvmsmallbg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/mvmlogo.png" alt="MVM logo"></div>

                    <blockquote>
                      „Unser Erfolg ist auch auf die hervorragende IT-Unterstu&#776;tzung durch Act! zuru&#776;ckzufu&#776;hren..."
                    </blockquote>
                    <a href="kundenreferenzen/mvm" title="Find out more about IT consultants benefiting from Act!" class="btn-second-white btn-white">Mehr erfahren</a>
                  </div>
                </div>
              </div>



                  <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/en-uk/img/schochsmallbg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/en-uk/img/schochlogowhite.png" alt="Mvm logo"></div>

                    <blockquote>
                      „Die gro&szlig;e St&auml;rke von Act! ist seine starke Flexibilit&auml;t in Unternehmensprozessen..."
                    </blockquote>
                    <a href="kundenreferenzen/schoch-werkhaus" title="" class="btn-second-white btn-white">Mehr erfahren</a>
                  </div>
                </div>
              </div>

                <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="" data-test-size="1-10" data-test-solution="actpro" >
                <div class="test-popout" style="background-image:url('/de-de/img/color-business-bg.jpg');">
                  <div class="box">
                    <div class="img-container">
                      <img src="/de-de/img/color-business-centers-white.png" alt="Mvm logo"></div>

                    <blockquote>
                      „Wir wollten ein System, das mit dem Unternehmen mitw&auml;chst..."
                    </blockquote>
                    <a href="kundenreferenzen/color-business-centers" title="" class="btn-second-white btn-white">Mehr erfahren</a>
                  </div>
                </div>
              </div>



