          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/rebokbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/reeboklogo.png" alt="reebok sports club logo"></div>

                <blockquote>
                  „Ohne Act! würden wir es nicht schaffen, jedes Jahr 5000 neue Mitglieder zu gewinnen“
                </blockquote>
                <a href="kundenreferenzen/reebok" title="Act! Referenzkunde Reebok" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('img/bg-referenzkunde-crm-software-fleischwaren.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/mcj-casings-logo.png" alt="mcj-casings logo"></div>

                <blockquote>
                  „Dank Act! können wir unsere Verkaufsgespräche viel besser planen!“
                </blockquote>
                <a href="kundenreferenzen/mcj-casings" title="Act! Referenzkunde MCJ Casings" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/corkers-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/corkers-logo.png" alt="corkers logo"></div>

                <blockquote>
                  „Swiftpage half mir, unser System an unsere spezifischen Bedürfnisse anzupassen.“
                </blockquote>
                <a href="kundenreferenzen/corkers" title="Act! Referenzkunde Corkers" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
            <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="information" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/limefresh-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/limefresh-logo.png" alt="limefresh logo"></div>

                <blockquote>
                  „Act! ermöglicht uns, Anzeigenkunden genau zum richtigen Zeitpunkt anzusprechen.“
                </blockquote>
                <a href="kundenreferenzen/limefresh" title="Act! Referenzkunde Limefresh" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>


      <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/man-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/connectvendinglogoWHITE.png" alt="connect vending logo"></div>

                <blockquote>
                 „Dank Act! konnten wir den Aufbau unserer internen Systeme verbessern..."
                </blockquote>
                <a href="kundenreferenzen/connect-vending" title="Act! Referenzkunde Connect Vendig" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Informationstechnologie" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/bg-referenzkunde-crm-software-automaten.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/ManessenslogoWHITE.png" alt="manessens logo"></div>

                <blockquote>
                  „Unsere Wahl fiel auf das Kontaktmanagementsystem Act!, da wir mit dieser Software die M&ouml;..."
                </blockquote>
                <a href="kundenreferenzen/manessens" title="Act! Referenzkunde Manessens" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>
           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/rayburns-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/rayburns-logo.png" alt="Rayburns logo"></div>

                <blockquote>
                 „Die Software ist schnell, professionell und kostengu&#776;nstig und hat unsere Produktivit&auml;t auf eine neue Stufe gehoben"
                </blockquote>
                <a href="kundenreferenzen/rayburns" title="Act! Referenzkunde Rayburns" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Informationstechnologie" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/morningside-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/morningside-logo.png" alt="Morningside logo"></div>

                <blockquote>
                  „Act! stellt uns die ben&ouml;tigten Informationen schnell und pr&auml;zise zur Verfu&#776;gung ..."
                </blockquote>
                <a href="kundenreferenzen/morningside" title="Act! Referenzkunde Morningside" class="btn-second-white btn-white">Mehr erfahren</a>
              </div>
            </div>
          </div>