      <footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Pourquoi choisir</span>

      				<ul>
      					<li>
      						<a href="pourquoi-choisir" title="Pourquoi choisir la solution Act!">Pourquoi choisir Act!</a>
      					</li>
      					<li>
      						<a href="temoignages" title="Ils utilisent le CRM Act!">Témoignage clients</a>
      					</li>

      				</ul>

      			</div>

      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title" title="Produits Act!">Produits</span>

      				<ul>
      					<li>
      						<a href="produits" title="Comparez les produits Act!">Comparez nos produits</a>
      					</li>
      					<li>
      						<a href="produits/act-pro" title="Découvrir Act! Pro">Act! Pro</a>
      					</li>
      					<li>
      						<a href="produits/act-premium" title="Découvrir Act! Premium">Act! Premium</a>
      					</li>
      				<!--	<li>
      						<a href="products/act-cloud">Act! Cloud</a>
      					</li>-->

              <!--  <li>
                  <a href="#">Mobilité</a></li>-->
      					<li>
      						<a href="produits/nouveautes" title="Nouveautés v16 de Act!">Nouveautés Act! v17</a>
      					</li>
      				</ul>

      			</div>
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Assistance</span>

      				<ul>
      					<li>
      						<a href="assistance" title="Assistance Act!">Business Care</a>
      					</li>

                <li>
                  <a href="assistance/obsolescence" title="Politique obsolescence de nos versions de logiciels">Politique d'obsolescence</a>
                </li>

                <li>
                  <a href="assistance/telechargements" title="Téléchargement Logiciel CRM" >Centre de téléchargement</a>
                </li>

      					<li>
      						<a href="http://kb-fr.swiftpage.com/" target="_blank">Knowledgebase</a>
      					</li>



      				</ul>

      			</div>



                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title"><a class="footwhite" href="http://www.swiftpage.com/fr-fr" target="_blank">À propos</a></span>
                              <ul>

                                          <li>  <a href="http://www.swiftpage.com/en-us/about/legal.shtml" target="_blank">Mentions légales</a></li>
                                          <li>  <a href="paiements"> Paiements</a></li>
                              </ul>

                        </div>

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title">Partenaires</span>
                              <ul>
                                    <li>
                                          <a href="partenaires">Trouver un partenaire</a>
                                    </li>
                              </ul>

                        </div>

      			<div class=" col-sm-2 social ">

      				<a href="https://www.youtube.com/user/ActStory" target="_blank" class="social-roll yt">Youtube</a>
      				<a href="https://www.linkedin.com/groups/?gid=1914089" class="social-roll linkd" target="_blank">LinkedIn</a>
      				<a href="https://twitter.com/actstory" class="social-roll twit" target="_blank">Twitter</a>
      				<a href="https://www.facebook.com/actcrm" class="social-roll fb" target="_blank">Facebook</a>

                              <br class="hidden-xs"><br class="hidden-xs"><br class="hidden-xs">



                              <img src="img/cards.jpg" style="max-width:100%;height:auto" class="hidden-xs"/>

                               <br><br>

                                                           <span class="copyright">&copy; 2015 Swiftpage ACT! LLC. Tous droits réservés. </span>

                            
      			</div>
      		</div>
      	</div>
      </footer>
