      <footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Pourquoi choisir</span>

      				<ul>
      					<li>
      						<a href="pourquoi-choisir" title="Pourquoi choisir la solution Act!">Pourquoi choisir Act!</a>
      					</li>
      					<li>
      						<a href="temoignages" title="Ils utilisent le CRM Act!">Témoignage clients</a>
      					</li>

      				</ul>

      			</div>

      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title" title="Produits Act!">Produits</span>

      				<ul>
      					<li>
      						<a href="produits" title="Comparez les produits Act!">Comparez nos produits</a>
      					</li>
      					<li>
      						<a href="produits/act-pro" title="Découvrir Act! Pro">Act! Pro</a>
      					</li>
      					<li>
      						<a href="produits/act-premium" title="Découvrir Act! Premium">Act! Premium</a>
      					</li>
                                          <li><a href="produits/act-emarketing/" title="Act! emarketing">Act! emarketing</a></li>
      				<!--	<li>
      						<a href="products/act-cloud">Act! Cloud</a>
      					</li>-->

              <!--  <li>
                  <a href="#">Mobilité</a></li>-->
      					<li>
      						<a href="produits/nouveautes" title="Nouveautés v16 de Act!">Nouveautés Act! v17</a>
      					</li>
      				</ul>

      			</div>
      			<div class="col-sm-2 hidden-xs">

      				<span class="foot_title">Assistance</span>

      				<ul>
      					<li>
      						<a href="assistance" title="Assistance Act!">Business Care</a>
      					</li>

                <li>
                  <a href="assistance/obsolescence" title="Politique obsolescence de nos versions de logiciels">Politique d'obsolescence</a>
                </li>

                <li>
                  <a href="assistance/telechargements" title="Téléchargement Logiciel CRM" >Centre de téléchargement</a>
                </li>

      					<li>
      						<a href="http://kb-fr.swiftpage.com/" target="_blank">Knowledgebase</a>
      					</li>

                                    <li>
                                          <a href="produits/systeme/">Configuration système</a>
                                    </li>

                            



      				</ul>

      			</div>



                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title"><a class="footwhite" href="http://www.swiftpage.com/fr-fr" target="_blank">À propos</a></span>
                              <ul>

                                          <li>  <a href="http://www.swiftpage.com/en-us/about/legal.shtml" target="_blank">Mentions légales</a></li>
                                          <li>  <a href="paiements"> Paiements</a></li>
                              </ul>

                        </div>

                        <div class="col-sm-2 hidden-xs">
                              <span class="foot_title">Partenaires</span>
                              <ul>
                                    <li>
                                          <a href="partenaires">Trouver un partenaire</a>
                                    </li>
                              </ul>

                        </div>

      			<div class=" col-sm-2 social ">

      				<a href="https://www.youtube.com/user/ActStory" target="_blank" class="social-roll yt">Youtube</a>
      				<a href="https://www.linkedin.com/groups/?gid=1914089" class="social-roll linkd" target="_blank">LinkedIn</a>
      				<a href="https://twitter.com/actstory" class="social-roll twit" target="_blank">Twitter</a>
      				<a href="https://www.facebook.com/actcrm" class="social-roll fb" target="_blank">Facebook</a>

                              <br class="hidden-xs"><br class="hidden-xs"><br class="hidden-xs">



                              <img src="img/cards.jpg" style="max-width:100%;height:auto" class="hidden-xs"/>

                               <br><br>

                                                           <span class="copyright">&copy; 2015 Swiftpage ACT! LLC. Tous droits réservés. </span>

                            
      			</div>
      		</div>
      	</div>
      </footer>
<script type="text/javascript">
function elqCreateOptInBanner() {
if (navigator.appVersion.indexOf('MSIE') != -1) {
var css = '.cookieBanner {z-index:30; position: absolute; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
}
else {
var css = '.cookieBanner {z-index:30; position: fixed; bottom: 0px; left: 0px; width: 100%; background-color:#444444; font-size:11px; font-family:verdana; color:#fff; padding:5px;} .cookieBannerText {float: left; text-align:left; width:96%;} .cookieButton {padding:3px 5px; background-color:#fff; border:0; font-size:11px; color:#362b22;font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;} .cookieClose {float:right; font-size:14px; font-weight:bold; cursor:pointer; padding-right:15px;color:#fff;} ';
}
var style = document.createElement('STYLE');
style.type = 'text/css';
if (style.styleSheet) {
style.styleSheet.cssText = css;
} else {
style.appendChild(document.createTextNode(css));
}
var head = document.getElementsByTagName('head')[0];
head.appendChild(style);
var div = document.createElement('div');
div.setAttribute('id', 'cookieBannerDiv');
div.className = 'cookieBanner';
div.innerHTML = '<div class="cookieBannerText">Notre site utilise des cookies qui permettent de personnaliser et d&rsquo;am&eacute;liorer votre experience sur notre site. Pour en savoir plus sur nos cookies, veuillez consulter notre <a href="politique-relative-aux-cookies/" style="text-decoration:underline;">Politique relative aux cookies</a>. En poursuivant votre navigation sur ce site, vous acceptez l&rsquo;utilisation de nos cookies.</div><div class="cookieClose" onclick="document.getElementById(\'cookieBannerDiv\').style.display = \'none\';">x</div>';
document.body.appendChild(div);

      // Hide alert after 20 seconds
      /*setTimeout(function(){
            $('.cookieClose').click();
      }, 20000);*/
}
</script>