<!--START FIXED NAV WRAPPER-->
<div class="fixed-wrapper">
  <!--START ORANGE TOP BAR-->
        <div class="topbar hidden-xs">
          	<div class="container">
              	<div class="col-sm-4 tl_links">
                  	<a href="essai" title="Télécharger la démo de Act!"> <strong>Essai gratuit &gt;</strong> </a>
				  	<a href="contact" title="Nous contacter"><strong>Nous contacter &gt;</strong></a>
                </div>
				<div class="col-sm-6 ">
                		<div class="hidden-sm ">
	                		France : <strong>09 75 18 23 09</strong>&nbsp;&nbsp;&nbsp;&nbsp;
	                		Belgique : <strong>078 483 840</strong>
                		</div>
              	</div>
			  	<div class="col-sm-2">
                		<nav>
               			<ul>
			   			 	<li >Langue : <strong class="lang_menu">Fran&#231;ais <span class="down_arrow hidden-sm"></span></strong>
			   			 		<ul>
                    				<li><a href="http://www.act.com/en-uk/" lang="en" hreflang="en" title="Act! CRM Software">English</a></li>
			   			 			<li><a href="http://www.act.com/de-de/" lang="de" hreflang="de" title="Act! CRM Software">Deutsch</a></li>
			   			 			<li><a href="http://act.com/?regLang=en-US" lang="en-us" hreflang="en-us" title="Act! CRM Software">English (U.S.)</a></li>
			   			 		</ul>
			   			 	</li>
			   			</ul>
                		</nav>
              	</div>
            </div>
         </div>
  <!--END ORANGE TOP BAR-->

  <!--START MAIN NAVIGATION (WHITE)-->
        <div class="container">
          	<div class="row">
          		<div class="col-sm-2 col-xs-12 mobile-menu">
            		<div class="row">
            			<div class="col-xs-10">
							<a href="/fr-fr/"><img  src="img/act-logiciel-crm-contacts.gif.gif" alt="Act! Logiciel CRM Contacts" class="actlogo"></a>
						</div>
		                <div class="trigger-overlay visible-xs col-xs-2" id="mobile_btn">
		                  	<div class="menu_icon"></div>
		                  	<div class="menu_icon_close"></div>
		                </div>
		            </div>
	            </div>
				<nav class="col-sm-10 nav-collapse">
					<ul>
						<li><a href="pourquoi-choisir">Pourquoi choisir</a>
							   <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="pourquoi-choisir" title="Pourquoi choisir Act! comme solution CRM ?">Pourquoi choisir Act!</a></li>
					  		 	<!--<li><a href="why-choose-act/cloud-on-premise-deployment">Deployment freedom</a></li>-->
								  <li><a href="temoignages" title="Ils utilisent notre logiciel de gestion de contacts">Témoignages clients</a></li>
					  		</ul>
						</li>
						<li><a href="produits" title="Produits et logiciels Act!">Produits</a>
                            <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="produits" title="Comparez nos produits">Comparez nos produits</a></li>
					  		 	<li><a href="produits/act-pro" title="Logiciel et solutions Act! Pro">Act! Pro</a></li>
					  		 	<li><a href="produits/act-premium" title="Logiciel CRM Act! Premium">Act! Premium</a></li>
					  		 	<!--<li><a href="#">Mobilité</a></li>-->
								<!--<li><a href="products/act-cloud">Act! Cloud</a></li>-->
					  		 	<li><a href="produits/nouveautes" title="Nouveautés Act!">Nouveautés Act! v17</a></li>
					  		</ul>
					  	</li>
					  	<li><a href="assistance" title="Assistance Act!">Assistance</a>

								<ul>
									<li><a href="assistance" title="Programme d'assistance">Business Care</a></li>
									<li><a href="assistance/obsolescence" title="Obsolenscence de nos logiciels CRM">Politique d'obsolescence</a></li>
									<li><a href="assistance/telechargements" title="Centre de téléchargement">Centre de téléchargement</a></li>
									<li><a href="http://kb-fr.swiftpage.com/" target="_blank">Knowledgebase</a></li>

								</ul>
						</li>
					  	<li><a href="partenaires" title="Nos partenaires">Partenaires</a></li>
				  		<li><a href="http://www.swiftpage.com/fr-fr" target="_blank">&Agrave; propos</a></li>
                		<li><a href="contact" title="Nous contacter">Nous contacter</a></li>
					</ul>
					<br style="clear:both">
				</nav>


			</div>
        </div>
  <!--END MAIN NAVIGATION-->
</div>
<div class="spacer"></div>
<!--END FIXED WRAPPER-->
