
<!--START FIXED NAV WRAPPER-->        
<div class="fixed-wrapper">
  	<div class="container mobile-menu">

		  		<div class="col-md-2 col-lg-1 col-xs-12 col-sm-2 ">
			  		<div class="row">
            		<div class="col-xs-10 col-md-12">
							<a href="/fr-fr/"><img  src="img/act-logiciel-crm-contacts.gif" alt="Act! Logiciel CRM Contacts" class="actlogo"></a>
					</div>
					<div class="trigger-overlay visible-xs col-xs-2" id="mobile_btn">
		        	    <div class="menu_icon"></div>
		        	    <div class="menu_icon_close"></div>
		        	</div>
			  		</div>
				</div>

				<nav class="col-md-6 col-sm-10 col-lg-5 nav-collapse">
					<ul>
						<li><a href="pourquoi-choisir">Pourquoi choisir&nbsp;&nbsp;<span class="down_arrow"></span></a>
							   <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="pourquoi-choisir" title="Pourquoi choisir Act! comme solution CRM ?">Pourquoi choisir Act!</a></li>
					  		 	<!--<li><a href="why-choose-act/cloud-on-premise-deployment">Deployment freedom</a></li>-->
								  <li><a href="temoignages" title="Ils utilisent notre logiciel de gestion de contacts">Témoignages clients</a></li>
					  		</ul>
						</li>
						<li><a href="produits" title="Produits et logiciels Act!">Produits&nbsp;&nbsp;<span class="down_arrow"></span></a>
                            <!-- First Tier Drop Down -->
					  		<ul>
					  		 	<li><a href="produits" title="Comparez nos produits">Comparez nos produits</a></li>
					  		 	<li><a href="produits/act-pro" title="Logiciel et solutions Act! Pro">Act! Pro</a></li>
					  		 	<li><a href="produits/act-premium" title="Logiciel CRM Act! Premium">Act! Premium</a></li>
					  		 	<li><a href="produits/act-emarketing/" title="Act! emarketing">Act! emarketing</a></li>
					  		 	<!--<li><a href="#">Mobilité</a></li>-->
								<!--<li><a href="products/act-cloud">Act! Cloud</a></li>-->
					  		 	<li><a href="produits/nouveautes" title="Nouveautés Act!">Nouveautés Act! v17</a></li>
					  		</ul>
					  	</li>
					  	<li><a href="assistance" title="Assistance Act!">Assistance&nbsp;&nbsp;<span class="down_arrow"></span></a>

								<ul>
									<li><a href="assistance" title="Programme d'assistance">Business Care</a></li>
									<li><a href="assistance/obsolescence" title="Obsolenscence de nos logiciels CRM">Politique d'obsolescence</a></li>
									<li><a href="assistance/telechargements" title="Centre de téléchargement">Centre de téléchargement</a></li>
									<li><a href="http://kb-fr.swiftpage.com/" target="_blank">Knowledgebase</a></li>

								</ul>
						</li>
					  	<li><a href="partenaires" title="Nos partenaires">Partenaires</a></li>
					</ul>
					<br style="clear:both">
				</nav>
				
				<div class="col-md-2 contact_no hidden-xs hidden-md hidden-sm">
					<div class="header-countries">
	                		France : <strong>09 75 18 23 09</strong><br />
	                		Belgique : <strong>078 483 840</strong>
					</div>
				</div>
				
				<div class="col-md-3 col-sm-9 tl_links hidden-xs">
                	<a href="contact" title="Nous contacter" class="btn btn-second">Contact</a>
                  	<a href="essai" title="Télécharger la démo de Act!" class="btn btn-second">Essai gratuit </a>
				</div>
				<div class="col-sm-1">
					<nav class="langmenu">
						<ul>
			   			 	<li >Langue&nbsp;: <strong class="lang_menu">Fran&#231;ais <span class="down_arrow hidden-sm"></span></strong>
								<ul>
                    				<li><a href="http://www.act.com/en-uk/" lang="en" hreflang="en" title="Act! CRM Software">English</a></li>
			   			 			<li><a href="http://www.act.com/de-de/" lang="de" hreflang="de" title="Act! CRM Software">Deutsch</a></li>
			   			 			<li><a href="http://www.act.com/nl-nl/" lang="nl" hreflang="nl" title="Act! CRM Software">Nederlands</a></li>
			   			 			<li><a href="http://www.act.com/?regLang=en-US" lang="en-us" hreflang="en-us" title="Act! CRM Software">U.S. English</a></li>
								</ul>
							</li>
						</ul>
					</nav>
				</div>

    </div>
</div>
<div class="spacer"></div>
<!--END FIXED WRAPPER-->