<div class="slider-container">
 <div class="slider ">
 <ul>
 <li class="cta">
 <div class="slider-bg">
 <img src="img/femme-heureuse-avec-act.jpg" alt="Du bonheur avec Act!" />
 </div>

 <div class="slider-overlay">
 <div class="container ">
 <div class="row section">
 <div class="col-sm-7 col-left bottom mb-center">
 <h1 class="large_strapline_home semibold"><strong>Num&eacute;ro 1 </strong> des logiciels de gestion des contacts</h1>
 <div class="btn-bottom">
 <a href="essai" title="Télécharger la démo de Act!" class="btn-primary btn">essai gratuit</a>
 <a href="demo" title="Démonstration personnalisée Act!" class="btn-second btn">Demande de d&eacute;mo</a>
 <a target="_blank" href="http://store.act.com/app/site/backend/intl/additemtocart.nl?buyid=3001&qty=1&selcurrency=4&selsubsidiary=7&selshopperlanguage=fr_FR" class="btn-second btn">acheter <span class="uppercase">A</span>ct!</a>
 </div>
 </div>
 <div class="col-sm-4 imagefix hidden-xs">

 </div>
 </div>
 </div>
 </div>
 </li>




  <li class="cta">
    <div class="slider-bg">
      <img src="img/equipe-marketing-reunion.jpg" alt="Equipe marketing Réunion" />
    </div>

    <div class="slider-overlay">
      <div class="container ">
        <div class="row section">
            <div class="col-sm-7 col-left bottom mb-center">
                <span class="large_strapline_home semibold"><strong>G&eacute;rez vos contacts,</strong> prospectez et fid&eacute;lisez vos clients</span>
           <div class="btn-bottom">
             <a href="essai" title="Télécharger la démo de Act!" class="btn-primary btn">essai gratuit</a>
			 <a href="demo" title="Démonstration personnalisée Act!" class="btn-second btn">Demande de d&eacute;mo</a>
             
              </div>
           </div>
            <div class="col-sm-4 imagefix hidden-xs">

                       </div>
        </div>
      </div>
    </div>
  </li>



 <li class="cta">
 <div class="slider-bg">
 <img src="img/reebok-utilise-act-prospects.jpg" alt="Reebok utilise Act! Pour ses prospects" />
 </div>
 <div class="slider-overlay">
 <div class="container ">
 <div class="row section">
 <div class="col-sm-8 col-left white bottom col-left mb-center">
 <span class="large_strapline_home semibold"> "Act!, l'outil commercial qui a du tonnus" </span>
 <img src="img/reebok.png" alt="" width="160" class="hidden-xs">
 <span class="hidden-xs"><br><br></span>


 <div class="btn-bottom white">
 <a href="temoignage/reebok" title="Témoignage CRM Reebok" class="btn-primary btn">en savoir plus</a>
 <a href="temoignages" title="Ils utilisent notre logiciel de gestion de contacts" class="btn-second btn">tous nos t&eacute;moignages</a>
 </div>
 </div>
 <div class="col-sm-4 imagefix hidden-xs"></div>
 </div>
 </div>
 </div>
 </li>













 </ul>
 </div>
 </div>
