<div class="slider-container">
 <div class="slider ">
 <ul>
 <li class="cta">
 <div class="slider-bg">
 <img src="img/businessmen-satisfied-using-act.jpg" alt="Du bonheur avec Act!" />
 </div>

 <div class="slider-overlay">
 <div class="container ">
 <div class="row section">
 <div class="col-sm-7 col-left bottom mb-center">
 <h1 class="large_strapline_home semibold"><strong>Num&eacute;ro 1 </strong> des logiciels de gestion des contacts</h1>
 <div class="btn-bottom">
 <a href="essai" title="Télécharger la démo de Act!" class="btn-primary btn">essai gratuit</a>
 <a href="demo" title="Démonstration personnalisée Act!" class="btn-second btn">Demande de d&eacute;mo</a>
 <a target="_blank" href="http://store.act.com/app/site/backend/intl/additemtocart.nl?buyid=8092&qty=1&selcurrency=4&selsubsidiary=7&selshopperlanguage=fr_FR" class="btn-second btn">acheter <span class="uppercase">A</span>ct!</a>
 </div>
 </div>
 <div class="col-sm-4 imagefix hidden-xs">

 </div>
 </div>
 </div>
 </div>
 </li>




  <li class="cta">
    <div class="slider-bg">
      <img src="img/equipe-marketing-reunion.jpg" alt="Equipe marketing Réunion" />
    </div>

    <div class="slider-overlay">
      <div class="container ">
        <div class="row section">
            <div class="col-sm-7 col-left bottom mb-center">
                <span class="large_strapline_home semibold"><strong>G&eacute;rez vos contacts,</strong> prospectez et fid&eacute;lisez vos clients</span>
           <div class="btn-bottom">
             <a href="essai" title="Télécharger la démo de Act!" class="btn-primary btn">essai gratuit</a>
			 <a href="demo" title="Démonstration personnalisée Act!" class="btn-second btn">Demande de d&eacute;mo</a>
             
              </div>
           </div>
            <div class="col-sm-4 imagefix hidden-xs">

                       </div>
        </div>
      </div>
    </div>
  </li>



 <li class="cta">
 <div class="slider-bg">
 <img src="img/act-for-color-business-centers.jpg" alt="Reebok utilise Act! Pour ses prospects" />
 </div>
 <div class="slider-overlay">
 <div class="container ">
 <div class="row section">
 <div class="col-sm-8 col-left bottom col-left mb-center">
 <span class="large_strapline_home semibold">Act!, la solution bien agenc&eacute;e !</span>
 <img src="img/color-business-centers.png" alt="" width="160" class="hidden-xs">
 <span class="hidden-xs"><br><br></span>


 <div class="btn-bottom">
 <a href="temoignage/color-business-centers" class="btn-primary btn">en savoir plus</a>
 <a href="temoignages" title="Ils utilisent notre logiciel de gestion de contacts" class="btn-second btn fill-white">tous nos t&eacute;moignages</a>
 </div>
 </div>
 <div class="col-sm-4 imagefix hidden-xs"></div>
 </div>
 </div>
 </div>
 </li>
 <li class="cta">
  <div class="slider-bg playVideo">
    <img src="img/femme-heureuse-avec-act.jpg" alt="Video: salesman using Act! Contact Management software" />
  </div>

  <div class="slider-overlay playVideo">
    <div class="container ">
      <div class="row section ">
          <div class="col-sm-9 col-left bottom mb-center col-xs-12">
            <span class="large_strapline_home semibold playVideo"><strong>D&eacute;couvrez comment </strong><br>Act! peut aider votre entreprise</span>
          <div class="btn-bottom">
              <a  class="playVideo btn-primary btn">Regarder</a>
          </div>
        </div>
        <div class="col-sm-4 imagefix hidden-xs"> </div>
      </div>
    </div>
  </div>
 </li>












 </ul>
 </div>
 </div>
