          <div class="col-sm-4 test-wrap" data-test-cat="sportswear" data-test-size="1-10" data-test-solution="product 1" > 
              <div class="test-popout" style="background-image:url('img/rebokbg.jpg');">
                <div class="box">
              <div class="img-container"><img src="img/reeboklogo.png" alt="reebok sports club logo"></div>
              <h5>Your contacts and time</h5>
                    <blockquote>"I know that if we didn't have Act!, we wouldn't comeclose to achieving the 5,000 new memberships we sign up every year."
              <cite>Sales and Marketing Director Diane Kay</cite>
              <div class="comp_name">Reebok Sports Club</div>
            </blockquote>
                    <a href="testimonials/reebok" class="btn-second-white btn-white">Find out more</a>
                </div>
         </div>
            </div>
            <div class="col-sm-4 test-wrap" data-test-cat="sportswear" data-test-size="1-10" data-test-solution="product 1" > 
              <div class="test-popout"  style="background-image:url('img/rebokbg.jpg');">
                <div class="box">
            <div class="img-container"><img src="img/mcj-casings-logo.png" alt="reebok sports club logo"></div>
              <h5>Your contacts and time</h5>
                    <blockquote>"With Act! all members of our sales team can find out everything they need to know about a customer at the touch of a button, so relationships flow much more smoothly."
              <cite>Angela Banks, Sales Manager, MCJ Casings</cite>
              <div class="comp_name">MCJ Casings</div>
            </blockquote>
                    <a href="testimonials/mcj-casings" class="btn-second-white btn-white">Find out more</a>
                </div>
         </div>
            </div>
            <div class="col-sm-4 test-wrap" data-test-cat="sportswear" data-test-size="1-10" data-test-solution="product 1" > 
              <div class="test-popout" style="background-image:url('img/corkers-bg.jpg');">
                <div class="box">
            <div class="img-container"><img src="img/corkers-logo.png" alt="reebok sports club logo"></div>
              <h5>Your contacts and time</h5>
                    <blockquote>"Recently, I wanted to track which prospects had been sent samples. Swiftpage helped me customise our system so now I can run reports with exactly the information I'm looking for."
              <cite>Kate Bavester, Office Manager, Corkers Crisps</cite>
              <div class="comp_name">Corkers Crisps</div>
            </blockquote>
                    <a href="testimonials/corkers" class="btn-second-white btn-white">Find out more</a>
                </div>
         </div>
            </div>
