          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/rebokbg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/reeboklogo.png" alt="reebok sports club logo"></div>

                <blockquote>
                  "Je r&eacute;alise que sans Act!, nous n&rsquo;arriverions pas &agrave; atteindre les 5 000 nouveaux abonnements par an..."
                </blockquote>
                <a href="temoignage/reebok" title="Témoignage CRM Reebok" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout"  style="background-image:url('img/bg-temoignage-client-logiciel-boyaux.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/mcj-casings-logo.png" alt="mcj-casings logo"></div>

                <blockquote>
                  "Avec Act!, nos commerciaux ont acc&egrave;s &agrave; toutes les donn&eacute;es essentielles en un clic..."
                </blockquote>
                <a href="temoignage/mcj-casings" title="Cas client prospection" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="manufacturing" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/corkers-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/corkers-logo.png" alt="corkers logo"></div>

                <blockquote>
                  "Derni&egrave;rement, j&rsquo;ai cherch&eacute; &agrave; trier les prospects &agrave; qui on avait envoy&eacute; des &eacute;chantillons..."
                </blockquote>
                <a href="temoignage/corkers" title="Témoignage entreprise familiale" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>

            <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="information" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/limefresh-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/limefresh-logo.png" alt="limefresh logo"></div>

                <blockquote>
                  "Chaque jour, Act! nous permet de communiquer avec nos clients ou des annonceurs potentiels au moment propice..."
                </blockquote>
                <a href="temoignage/limefresh" title="Témoignage client édition" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/man-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/connectvendinglogoWHITE.png" alt="limefresh logo"></div>

                <blockquote>
                  "Act! nous a aid&eacute; &agrave; am&eacute;liorer la structure de nos syst&egrave;mes internes..."
                </blockquote>
                <a href="temoignage/connect-vending" title="Cas client CRM distribution" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Informatique" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/bg-client-distributeurs-automatiques.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/ManessenslogoWHITE.png" alt="limefresh logo"></div>

                <blockquote>
                  "Nous avons choisi la solution Act! pour la grande latitude de parame&#769;trage qu&rsquo;elle..."
                </blockquote>
                <a href="temoignage/manessens" title="Référence client CRM" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="services" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/rayburns-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/rayburns-logo.png" alt="Rayburns logo"></div>

                <blockquote>
                  "Act! est une solution rapide, rus&eacute;e et &eacute;conomique qui a compl&egrave;tement boost&eacute; notre productivit&eacute;."
                </blockquote>
                <a href="temoignage/rayburns" title="Cas client CRM distribution" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>

           <div class="col-sm-4 col-md-3 test-wrap" data-test-cat="Informatique" data-test-size="1-10" data-test-solution="actpro" >
            <div class="test-popout" style="background-image:url('img/morningside-bg.jpg');">
              <div class="box">
                <div class="img-container">
                  <img src="img/morningside-logo.png" alt="Morningside logo"></div>

                <blockquote>
                  "Avec Act!, nous avons les informations dont nous avons besoin sous la main ..."
                </blockquote>
                <a href="temoignage/morningside" title="Référence client CRM" class="btn-second-white btn-white">en savoir plus</a>
              </div>
            </div>
          </div>